### ISSUE TITLE
start/reload/stop behaviour.

### ISSUE THREAD

**Issue by xbello** [bung87/daemon#2]
I was wondering if the intended behaviour for the start, reload and stop function is the following:

```Nim
import os
import daemonim

proc main() {.noconv.} =
  while true:
    echo "Running!"
    sleep(5000)

when isMainModule:
  let command = commandLineParams()[0]
  var d = initDaemon("daemonim.pid")
  d.handler = main

  case command
  of "start":
    d.start()
  of "restart":
    d.restart()
  of "stop":
    d.stop()
  else:
    echo "Command not recognized: " & command
```

That is: you have a binary that reads the pidfile (in this case `daemonim.pid`), and acts on the process that have that pid, even if it's launched from other terminal. For instance, you can launch nginx to serve with `# nginx`, and later reload the daemon with `# nginx reload` or stop it with `# nginx stop`, IIRC.

With the code as it is now, the above `d.stop()` call doesn't work as expected. It launches a new daemon (with another pid), kills itself, and exits, but the old daemon keeps running.

Or maybe the intention is to do the starts/stops within the same binary, and the daemon can only be stopped either reaching condition in the same code, or killing it externally with `kill`, never with e.g. `myDaemon stop`.

**Comment by bung87** [comment]
in this case you may have some message channel , in the daemon process listen to it , when it get stop command it stop itself, no matter where the message comming from. I checked the `python-daemon` it does not implement it, I dont know how nginx do this, it can be done just write some code.

I mean seperate the cli logic from daemon logic, as like you have a cli tool, and can start a daeomon as master process , send message to this process.

for exmaple like uwsgi you can have touch reload logic, monitoring a file, start your daemon, when file update reload itself. it triggered outside of the process.
